name: User Statistician

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run User Statistician
        uses: cicirello/user-statistician@v1.25.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-and-push: true
